name: project
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.12.0
  - ca-certificates=2024.6.2
  - cairo=1.16.0
  - certifi=2024.6.2
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - eigen=3.4.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ffmpeg=4.2.2
  - filelock=3.13.4
  - fontconfig=2.13.94
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.3.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - glib=2.80.0
  - glib-tools=2.80.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=68.2
  - idna=3.7
  - imagecodecs=2023.1.23
  - imageio=2.34.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=12.0.1
  - libcurl=8.1.2
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - libllvm12=12.0.1
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libopus=1.3.1
  - libpng=1.6.43
  - libpq=12.17
  - libprotobuf=4.25.1
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libtorch=2.1.2
  - libunistring=0.9.10
  - libuv=1.48.0
  - libvpx=1.10.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=18.1.3
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.3
  - nomkl=1.0
  - nspr=4.35
  - nss=3.98
  - numexpr=2.9.0
  - numpy=1.26.4
  - opencv=4.6.0
  - openh264=1.8.0
  - openjpeg=2.5.0
  - openssl=3.3.1
  - packaging=24.0
  - pandas=2.2.2
  - parso=0.8.4
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=24.0
  - pixman=0.43.4
  - platformdirs=4.2.1
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pygments=2.17.2
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.1.2
  - pytz=2024.1
  - pywavelets=1.4.1
  - pyzmq=26.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - scikit-image=0.22.0
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - seaborn=0.12.2
  - setuptools=69.5.1
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.12
  - tables=3.9.2
  - threadpoolctl=3.5.0
  - tifffile=2023.8.12
  - tk=8.6.13
  - torchvision=0.15.2
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - x264=1!152.20180806
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autograd==1.6.2
      - autograd-gamma==0.5.0
      - captum==0.7.0
      - formulaic==1.0.1
      - frozenlist==1.4.1
      - future==1.0.0
      - imbalanced-learn==0.12.2
      - imblearn==0.0
      - interface-meta==1.3.0
      - lifelines==0.28.0
      - multidict==6.0.5
      - opencv-contrib-python==4.9.0.80
      - opencv-python==4.9.0.80
      - pyflann==1.6.14
      - torch-geometric==2.5.3
      - torchsummary==1.5.1
      - wrapt==1.16.0
      - yarl==1.9.4
